SportStore/Controllers/LoginUserController.cs
using SportStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStore.Controllers
{
    public class LoginUserController : Controller
    {
        private DBSportStoreEntities db = new DBSportStoreEntities();
        // GET: LoginUser
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginAccount(Customer _user)
        {
            var check = db.Customers.Where(s => s.NameCus == _user.NameCus && s.PassCus == _user.PassCus).FirstOrDefault();
            if (check == null)//   login sai thong tin
            {
                ViewBag.ErrorInfo = "Sai thông tin";
                return View("index");
            }
            else
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                Session["ID"] = _user.IDCus;
                Session["NameUser"] = _user.NameCus;
                Session["PasswordUser"] = _user.PassCus;
                return RedirectToAction("Index", "CustomerProducts");
            }
        }

        public ActionResult LoginAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LoginAdmin(AdminUser _user)
        {
            var check = db.AdminUsers.Where(s => s.NameUser == _user.NameUser && s.PasswordUser == _user.PasswordUser).FirstOrDefault();
            if (check == null)//   login sai thong tin
            {
                ViewBag.ErrorInfo = "Sai thông tin";
                return View("LoginAdmin");
            }
            else
            {
                db.Configuration.ValidateOnSaveEnabled = false;
                Session["ID"] = _user.ID;
                Session["NameUser"] = _user.NameUser;
                Session["PasswordUser"] = _user.PasswordUser;
                return RedirectToAction("Index", "Product");
            }
        }
        public ActionResult RegisterUser()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterUser(Customer _cus)
        {
            if (ModelState.IsValid)
            {
                var check_ID = db.Customers.Where(s => s.NameCus == _cus.NameCus).FirstOrDefault();
                if (check_ID == null)
                {
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.Customers.Add(_cus);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ErrorRegister = "ID đã tồn tại";
                    return View();
                }
            }
            return View();
        }
        public ActionResult LogOutUser()
        {
            Session.Abandon();
            return RedirectToAction("Index", "CustomerProducts");
        }
    }
}

SportStore/Views/LoginUser/Index.cshtml
@model SportStore.Models.Customer

@{
    ViewBag.Title = "Login";
    Layout = null;
}
<style>
    .field-validation-error {
        color: red;
    }

    #middle {
        padding-bottom: 100px;
        border: solid 1px blue;
        background-color: deepskyblue;
        background-position: center;
        background-attachment: fixed;
        margin: 0 30% 0 30%;
    }

    .loginfr {
        padding: 10px;
    }

    .labellg {
        margin-bottom: 2%;
    }

    .wrapbtn {
        text-align: center;
    }

    .btnregis {
        padding: 5px 50px 5px 50px;
        margin: 10px 0 0 0;
    }

    .btnlogin {
        margin: 10px 0 10px 0;
    }
</style>
<a href="~/CustomerProducts/Index"><div style="justify-content:center;display:flex;"><img class="img-fluid sp-custom-118-1628235565" src="~/Content/Images/logobrand.png" width="150" alt="FoxPRO" style="margin-bottom: 5px !important;"></div></a>
<div id="middle" style="background-color:ghostwhite">
    <h2 style="text-align:center">ĐĂNG NHẬP</h2>
    @using (Html.BeginForm("LoginAccount", "LoginUser"))
    {
        @Html.AntiForgeryToken()
        <div class="loginfr">
            <h3 class="labellg">Tên user</h3>
            <div>@Html.TextBoxFor(model => model.NameCus, new { style = "field-validation-error" })</div>
            <div>@Html.ValidationMessageFor(model => model.NameCus)</div>

            <h3 class="labellg">@Html.LabelFor(model => model.PassCus)</h3>
            <div>@Html.EditorFor(model => model.PassCus)</div>
            <div>@Html.ValidationMessageFor(model => model.PassCus)</div>
            @if (ViewBag.ErrorInfo != null)
            {
                <p style="color:red;font-weight:bold;">@ViewBag.ErrorInfo</p>
            }

            <div><input class="btnlogin" type="submit" value="Login"></div>
        </div>
    }
    <div class="wrapbtn"> <a href="~/loginuser/loginadmin">
        <button class="btnregis">Đăng nhập dưới quyền admin</button></a>
    </div>
    <hr />
    <h3 style="text-align:center;">
        Hoặc
    </h3>
    <hr />
    <p style="text-align:center">Bạn chưa có tài khoản? Hãy đăng ký lẹ tay nào!</p>
    @using (Html.BeginForm("RegisterUser", "LoginUser"))
    {
        <div class="wrapbtn">
            <button class="btnregis" onclick="location.assign = '~/LoginUser/RegisterUser';">Tạo tạo khoản</button>
        </div>
    }

</div>

SportStore/Views/LoginUser/LoginAdmin.cshtml
@model SportStore.Models.AdminUser

@{
    ViewBag.Title = "Login";
    Layout = null;
}
<style>
    .field-validation-error {
        color: red;
    }

    #middle {
        padding-bottom: 100px;
        border: solid 1px blue;
        background-color: deepskyblue;
        background-position: center;
        background-attachment: fixed;
        margin: 0 30% 0 30%;
    }

    .loginfr {
        padding: 10px;
    }

    .labellg {
        margin-bottom: 2%;
    }

    .wrapbtn {
        text-align: center;
    }

    .btnregis {
        padding: 5px 50px 5px 50px;
        margin: 10px 0 0 0;
    }

    .btnlogin {
        margin: 10px 0 10px 0;
    }
</style>
<a href="~/CustomerProducts/Index"><div style="justify-content:center;display:flex;"><img class="img-fluid sp-custom-118-1628235565" src="~/Content/Images/logobrand.png" width="150" alt="FoxPRO" style="margin-bottom: 5px !important;"></div></a>
<div id="middle" style="background-color:ghostwhite">
    <h2 style="text-align:center">ĐĂNG NHẬP</h2>
    @using (Html.BeginForm("Loginadmin", "LoginUser"))
    {
        @Html.AntiForgeryToken()
        <div class="loginfr">
            <h3 class="labellg">Tên admin</h3>
            <div>@Html.TextBoxFor(model => model.NameUser, new { style = "field-validation-error" })</div>
            <div>@Html.ValidationMessageFor(model => model.NameUser)</div>

            <h3 class="labellg">@Html.LabelFor(model => model.PasswordUser)</h3>
            <div>@Html.EditorFor(model => model.PasswordUser)</div>
            <div>@Html.ValidationMessageFor(model => model.PasswordUser)</div>
            @if (ViewBag.ErrorInfo != null)
            {
                <p style="color:red;font-weight:bold;">@ViewBag.ErrorInfo</p>
            }

            <div><input class="btnlogin" type="submit" value="Login"></div>
        </div>
    }
</div>

SportStore/Views/LoginUser/RegisterUser.cshtml
@model SportStore.Models.Customer

@{
    ViewBag.Title = "RegisterUser";
    Layout = null;
}
<style>
    body {
        background: #DDD8D3;
    }

    .regislabel {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-items:center;
    }

    .wraplable {
        float: left;
        width: 45%;
        min-height: 750px;
    }

    .field-validation-error {
        color: red;
    }
    .contentmd {
        margin-left: 5px;
    }
    #middles {
        margin-block: auto;
        margin-inline: auto;
        float: right;
        width: 50%;
        background:white;
        min-height: 500px;
        border: 2px solid black;
        border-radius: 30px;
        padding: 10px;
    }
</style>
@using (Html.BeginForm("RegisterUser", "LoginUser", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="wraplable">
    <a class="navbar-brand ps-3" href="~/CustomerProducts/Index">
        <img class="img-fluid sp-custom-118-1628235565" src="~/Content/Images/logobrand.png" width="150" alt="FoxPRO" style="margin-bottom: 5px !important;">
    </a>
    <div class="regislabel">
        <h1>
            Xin chào <br /> Quý khách.
        </h1>
        <p>Tạo tài khoản FoxPRO để đăng nhập vào tất cả trang web của FoxPRO và đối tác nhanh chóng!</p>
    </div>
</div>
    <div id="middles">
        <div class="contentmd">
            <div> <h1 style="text-align:center">ĐĂNG KÝ</h1></div>
            @Html.AntiForgeryToken()

            <p>@Html.LabelFor(model => model.NameCus)</p>
            <p>@Html.TextBoxFor(model => model.NameCus,new { @style = "width: 100%; padding:10px;", placeholder = "Nhập họ và tên" })</p>
            <p>@Html.ValidationMessageFor(model => model.NameCus)</p>

            <p>@Html.LabelFor(model => model.PassCus)</p>
            <p>@Html.PasswordFor(model => model.PassCus, new { @style = "width: 100%; padding:10px;", placeholder = "Nhập mật khẩu" })</p>
            <p>@Html.ValidationMessageFor(model => model.PassCus)</p>

            <p>@Html.LabelFor(model => model.ConfirmPass)</p>
            <p>@Html.PasswordFor(model => model.ConfirmPass, new { @style = "width: 100%; padding:10px;"})</p>
            <p>@Html.ValidationMessageFor(model => model.ConfirmPass)</p>
            @if (ViewBag.ErrorRegister != null)
            {
                <p style="color:red;font-weight:bold;">@ViewBag.ErrorRegister</p>
            }


            <p>@Html.LabelFor(model => model.PhoneCus)</p>
            <p>@Html.TextBoxFor(model => model.PhoneCus, new { @style = "width: 100%; padding:10px;", placeholder = "Nhập họ và tên" })</p>
            <p>@Html.ValidationMessageFor(model => model.PhoneCus)</p>

            <p>@Html.LabelFor(model => model.EmailCus)</p>
            <p>@Html.TextBoxFor(model => model.EmailCus,new { @style = "width: 100%; padding:10px;", placeholder = "Nhập họ và tên" })</p>
            <p>@Html.ValidationMessageFor(model => model.EmailCus)</p>

            <input type="submit" value="TẠO TÀI KHOẢN" style="padding: 10px; width: 100%; background: #2E2E2E; color: white; border-radius: 30px; " />
        </div>
    </div>
}