SportStore/Controllers/CustomerProductsController.cs
using PagedList;
using SportStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SportStore.Controllers
{
    public class CustomerProductsController : Controller
    {
        private DBSportStoreEntities db = new DBSportStoreEntities();
        // GET: CustomerProducts
        public ActionResult Index(string category, int? page, string SearchString, double min = double.MinValue, double max = double.MaxValue)
        {
            //Tìm kiếm chuỗi truy vấn theo category
            //var products = db.Products.Include(p => p.Category);

            //Tìm kiếm chuỗi truy vấn theo NamePro, nếu chuỗi truy vấn SearchString khác rỗng, null
            //if (!String.IsNullOrEmpty(SearchString))
            //{
            //    products = products.Where(s => s.NamePro.Contains(SearchString));
            //}

            //Tìm kiếm chuỗi truy vấn theo NamePro(SearchString)
            // Tìm kiếm chuỗi truy vấn theo đơn giá
            //Khai báo mỗi trang 4 sản phẩm
            //Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            //Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            //Nếu page = null thì đặt lại page là 1.
            //Trả về các product được phân trang theo kích thước và số trang.
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            if (page == null) page = 1;

            if (category == null)
            {
                var productList = db.Products.OrderByDescending(x => x.NamePro);
                return View(productList.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                var productList = db.Products.OrderByDescending(x => x.NamePro).Where(p => p.Category == category);
                return View(productList.ToPagedList(pageNumber, pageSize));
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new
               HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

    }
}

SportStore/Views/CustomerProducts/Details.cshtml
@model SportStore.Models.Product
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div style="margin: 10px auto; width: 70%;">
    <h2 style="text-align: center">CHI TIẾT SẢN PHẨM</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <img style="width: 100%;" src="@Url.Content(Model.ImagePro)">
        </div>
        <div class="col-md-6">
            <h4>Tên sản phẩm: @Model.NamePro</h4>
            <p style="text-align: justify">
                <span style="font-weight: bold">Mô tả:</span> @Model.DecriptionPro
            </p>
            <p class="price">
                Giá bán: <span style="color:red; font-size:24px;">
                    @Model.Price VNĐ
                </span>
            </p>
            <a class="btn btn-primary" href="@Url.Action("AddToCart", "ShoppingCart", new { id = Model.ProductID })">
                ĐẶT MUA
            </a>
        </div>
    </div>
</div>

SportStore/Views/CustomerProducts/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<SportStore.Models.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="w3-content w3-display-container">
    <img class="mySlides" src="~/Content/Images/banner1.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner2.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner3.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner4.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner5.png" style="width:100%">
</div>
<script>
    var slideIndex = 0;
    carousel();
    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > x.length) { slideIndex = 1 }
        x[slideIndex - 1].style.display = "block";
        setTimeout(carousel, 2000); // Change image every 2 seconds
    }
</script>
<br />
@*@using (Html.BeginForm("ProductList", "Products", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    Tên Sản phẩm : <input type="text" name="SearchString" />
                    <input type="submit" value="Tìm kiếm" class="btn btn-warning" />
                </td>
            </tr>
        </table>
    }*@
<h2 style="margin-left: 10px">DANH SÁCH SẢN PHẨM</h2>
<div class="row">
    @foreach (var sanpham in Model)
    {
        <div class="col-lg-3 col-md-6 mb-3">
            <div class="card h-100">
                <img class="card-img-top"
                     src="@Url.Content(sanpham.ImagePro)">
                <div class="card-body" style="text-align: center">
                    <h5 class="card-title">@sanpham.NamePro</h5>
                    <p class="card-text">@sanpham.Price <b>VNĐ</b></p>
                    <a href="/ShoppingCart/AddToCart/@sanpham.ProductID" class="btn btn-danger"> Mua </a>
                    @Html.ActionLink("CHI TIẾT", "Details", new { id = sanpham.ProductID }, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    }
</div>
<div class="phantrang">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div>@Html.PagedListPager(Model, page => Url.Action("Index", "CustomerProducts", new { page = page }))</div>
</div>
<style>
    #phantrang {
        margin-left: 200px;
    }
</style>

SportStore/Views/CustomerProducts/SearchOption.cshtml
@model IEnumerable<SportStore.Models.Product>
<div style="margin-top:-10px"></div>
@using (Html.BeginForm("SearchOption", "CustomerProducts"))
{
    <div class="w3-content w3-display-container">
    <img class="mySlides" src="~/Content/Images/banner1.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner2.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner3.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner4.png" style="width:100%">
    <img class="mySlides" src="~/Content/Images/banner5.png" style="width:100%">
</div>
<script>
    var slideIndex = 0;
    carousel();
    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > x.length) { slideIndex = 1 }
        x[slideIndex - 1].style.display = "block";
        setTimeout(carousel, 2000); // Change image every 2 seconds
    }
</script>
<br />
    <h2 style="margin-left: 10px">DANH SÁCH SẢN PHẨM</h2>
    <text>Từ</text>
    <input type="number" name="min" />
    <text>Đến</text>
    <input type="number" name="max" />
    <input type="submit" value="Search" />
    <div class="container" style="margin-top: 20px">
        <div class="row">
            @foreach (var sanpham in Model)
            {
                <div class="col-lg-3 col-md-6 mb-3">
                    <div class="card h-100">
                        <img class="card-img-top"
                             src="@Url.Content(sanpham.ImagePro)">
                        <div class="card-body" style="text-align: center">
                            <h5 class="card-title">@sanpham.NamePro</h5>
                            <p class="card-text">@sanpham.Price <b>VNĐ</b></p>
                            <a href="/ShoppingCart/AddToCart/@sanpham.ProductID" class="btn btn-danger"> Mua </a>
                            @Html.ActionLink("CHI TIẾT", "Details", new { id = sanpham.ProductID }, new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
}